#ifndef SOTP_FS_CONFIG_MBEDOS
#define SOTP_FS_CONFIG_MBEDOS

#define PAL_USE_HW_ROT 0
#define PAL_USE_HW_RTC 0
#define PAL_USE_HW_TRNG 1
#define PAL_SIMULATOR_FLASH_OVER_FILE_SYSTEM 0
#define PAL_USE_INTERNAL_FLASH 1
#define PAL_USE_SECURE_TIME 1


#endif //SOTP_FS_CONFIG_MBEDOS
